export type { AdaptadorAerolinea, ModoAdaptador, ParamsBusqueda, ResultadoAdaptador } from "./adaptador";
export { REGISTRO, adaptadorPorIata } from "./adapters";
export { abrirNavegador } from "./navegador";
export type { BrowserContext as ContextoNavegador, Page as Pagina } from "playwright";
export { consultarRobots, evaluarRobots } from "./robots";
export type { VeredictoRobots } from "./robots";
export { conReintentos, ErrorBloqueo, ErrorLectura, ErrorTimeout, ESPERAS_REINTENTO_MS, TIMEOUT_INTENTO_MS } from "./intento";
export type { RegistroIntento } from "./intento";
export { evidenciaParcial } from "./evidencia";
export { detectarBloqueo, verificarBloqueo, ESPERA_ASISTIDA_MS } from "./bloqueo";
export type { Bloqueo, ModoAsistido } from "./bloqueo";
export { esperarNavegacionAsistida, ESPERA_NAVEGACION_ASISTIDA_MS } from "./asistido";
export type { NavegacionAsistida } from "./asistido";
export type { AdaptadorMetabuscador, ParamsMetabuscador, ResultadoMetabuscador } from "./metabuscadores/contrato";
export { REGISTRO_METABUSCADORES, metabuscadorPorId } from "./metabuscadores";
