export * from "./modelos";
export * from "./configuracion";
export { distanciaKm } from "./geo";
export { Grafo } from "./grafo";
export type { Arista } from "./grafo";
export { expandirAeropuertos } from "./fase1-aeropuertos";
export type { ResultadoFase1 } from "./fase1-aeropuertos";
export { generarRutas } from "./fase2-rutas";
export type { ResultadoFase2 } from "./fase2-rutas";
export { analizarGaps } from "./fase3-gaps";
export type { EntradaFase3 } from "./fase3-gaps";
export { calcularCalendario, ventanasVerdes } from "./fase5-calendario";
export type { EntradaCalendario, Feriado } from "./fase5-calendario";
