export * from "./modelos";
export * from "./configuracion";
export { distanciaKm } from "./geo";
export { Grafo } from "./grafo";
export type { Arista } from "./grafo";
export { expandirAeropuertos } from "./fase1-aeropuertos";
export type { ResultadoFase1 } from "./fase1-aeropuertos";
export { generarRutas } from "./fase2-rutas";
export type { ResultadoFase2 } from "./fase2-rutas";
export { analizarGaps } from "./fase3-gaps";
export type { EntradaFase3 } from "./fase3-gaps";
export { calcularCalendario, puntuarDia, ventanasVerdes } from "./fase5-calendario";
export { diaSemana, domingoDePascua, enSemanaSanta, esUltimoDiaLibre, finDeSemanaLargoDe, temporadasDe } from "./fase5-demanda";
export { competenciaEfectivaDe, factorCompetencia, factorPorDias, kmEquivalentes, medirRuta } from "./fase7-indice";
export type { ConfigFase7, EntradaFase7, MedidaRuta } from "./fase7-indice";
export { priorizarRutas } from "./fase7-ranking";
export type { EntradaCalendario, Feriado } from "./fase5-calendario";
export { generarCombinaciones } from "./fase6-combinaciones";
export type { EntradaFase6 } from "./fase6-combinaciones";
export { generarSplitTickets } from "./fase2-split";
